openapi: 3.0.0
info:
  title: Glina Backend API
  description: API do backend da Glina para autenticação, produtos e investimentos.
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Ambiente local

paths:
  /auth/signup:
    post:
      summary: Criação de usuário
      tags: [Autenticação]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Usuário criado com sucesso
        '400':
          description: Erro de validação

  /auth/login:
    post:
      summary: Login do usuário
      tags: [Autenticação]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login realizado com sucesso
        '401':
          description: Credenciais inválidas

  /products:
    get:
      summary: Listar produtos
      tags: [Produtos]
      responses:
        '200':
          description: Lista de produtos

    post:
      summary: Criar um novo produto
      tags: [Produtos]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, description]
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Produto criado com sucesso
        '400':
          description: Erro de validação

  /investments:
    get:
      summary: Listar investimentos
      tags: [Investimentos]
      responses:
        '200':
          description: Lista de investimentos

    post:
      summary: Criar um novo investimento
      tags: [Investimentos]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId, productId]
              properties:
                userId:
                  type: string
                productId:
                  type: string
      responses:
        '200':
          description: Investimento criado com sucesso
        '400':
          description: Erro na transação

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
